### ISSUE TITLE
Opening in a new tab does not work in Firefox

### ISSUE THREAD

**Issue by DaveDuck321** [KennethSundqvist/key-jump-browser-extension#61]
Behavior: Links do not open at all when the '.' shortcut is used.
Expected: Links should open in a new tab.

OS: Manjaro Linux
Browser: Firefox (Chrome behaves as expected).

**Comment by KennethSundqvist** [comment]
Hi @DaveDuck321.

Thanks for reporting this issue.

This bug have been fixed in version 5.3.0 which was just released.
